<?php
/**
 * Implements hook_install().
 *
 * Set the default theme to the projects_harvard theme.
 */
function huji_front_install() {
  // Set the default theme.
  variable_set('theme_default', 'scholars_harvard');
}

/**
 * Enables iqss_scholars_front module.
 */
function huji_front_update_7001() {
  // Set the default theme.
  variable_set('theme_default', 'scholars_harvard');
  module_enable(array('iqss_scholars_front'));
}
