<?php
include_once('huji_front.features.inc');

/**
 * Implements hook_context_default_contexts_alter();
 */
function huji_front_context_default_contexts_alter(&$contexts){
  // Add extra boxes to the os_sitewide context
  if (isset($contexts['os_sitewide'])) {
    $fp_blocks = &$contexts['os_sitewide']->reactions['block']['blocks'];

    $fp_blocks['boxes-iqss_scholars_fixed_header'] = array(
      'module' => 'boxes',
      'delta' => 'iqss_scholars_fixed_header',
      'region' => 'header_top',
      'weight' => '-10',
    );
  }
}

/**
 * Implements hook_os_widget_alter().
 */
function huji_front_os_widget_alter(&$widget) {
  //Keep the default box instances that this module provides from getting used sitewide
  if($widget['module'] == 'boxes' && function_exists('huji_front_default_box')){
    static $fp_boxes;
    //Front Page Boxes
    if(!isset($fp_boxes)) $fp_boxes =  huji_front_default_box();

    if(isset($fp_boxes[$widget['delta']])){
      $widget['hidden'] = true;
    }
  }
}

/**
 * Implement hook_strongarm
 * Strongarm hook for configuration variables
 * for the os_stats block
 */
function huji_front_strongarm() {
	$export = array();

	$strongarm = new stdClass();
  	$strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  	$strongarm->api_version = 1;
  	$strongarm->name = 'os_stats_cache_expiration';
  	$strongarm->value = (int)3600*24;
  	$export['os_stats_cache_expiration'] = $strongarm;

	$strongarm = new stdClass();
  	$strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  	$strongarm->api_version = 1;
  	$strongarm->name = 'os_stats_enabled';
  	$strongarm->value = array(
  		'filesize' => 0,
  		'users' => 0,
  		'websites' => 1,
  		'posts' => 1,
  		'publications' => 0,
  		'files' => 1,
  	);
  	$export['os_stats_enabled'] = $strongarm;

  	return $export;
}

/**
 * Implements hook_preprocess_page().
 */
function huji_front_preprocess_page(&$vars) {
  if (vsite_get_vsite()) {
    return;
  }

  if (!drupal_is_front_page()) {
    return;
  }

  drupal_add_css(drupal_get_path('module', 'huji_front') . '/css/huji-front.css');

  // Remove branding header from sitewide front page.
  unset($vars['page']['branding_header']['huji']);

  // Show the login link.
  $vars['login_link'] = theme('openscholar_login');
}

/**
 * Implements hook_block_view_alter().
 */
function huji_front_block_view_alter(&$data, $block) {
  if ($block->delta != 'get_your_site_block') {
    return;
  }

  // Path of the "create site" button is different for logged out users.
  $path = _vsite_user_access_create_vsite() ? 'site/register' : 'https://docs.google.com/a/gizra.com/forms/d/1s_YBDIJKPp6CbqbmBJ-6RTtzU6jVjNwupAU5NOZD25I/viewform';
  $options = array(
    'attributes' => array(
      'class' => array(
        'get-your-site-button',
      ),
    ),
  );
  $data['content']['content']['#markup'] = l(t('Claim your site'), $path, $options);
}
