<?php

/**
 * @file
 * OpenScholar customization for The Hebrew University of Jerusalem.
 */

/**
 * Implements hook_menu_alter().
 */
function huji_menu_alter(&$item) {
  // Hide and neutralize the "Create new account and request new password" tab
  $item['user/register']['type'] = MENU_CALLBACK;
  $item['user/register']['access callback'] = FALSE;
  $item['user/password']['type'] = MENU_CALLBACK;
  $item['user/password']['access callback'] = FALSE;
}

/**
 * Implements hook_preprocess_page().
 */
function huji_preprocess_page(&$vars) {
  $vars['page']['branding_header']['huji'] = huji_branding_header();
  $vars['page']['branding_footer']['huji'] = huji_branding_footer();
}

/**
 * Returns if the active theme uses hwpi_basetheme as one of it's base theme.
 *
 * @return bool
 */
function _huji_is_hwpi_theme($theme_name = NULL) {
  if (is_null($theme_name)) {
    $theme_name = $GLOBALS['theme'];
  }
  $themes = list_themes();
  if (isset($themes[$theme_name])) {
    $t = $themes[$theme_name];
    if (isset($t->base_themes) && isset($t->base_themes['hwpi_basetheme'])) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Returns a build array for the HUJI branding header page region.
 *
 * @return array
 *   A build array ready to render header info.
 */
function huji_branding_header() {
  $header = array();
  $header['left_container'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'branding-left',
      ),
    ),
    'img' => array(
      '#theme' => 'link',
      '#path' => 'http://huji.ac.il',
      '#text' => theme('image', array('path' => drupal_get_path('module', 'huji') . '/images/logo.png', 'width' => 398, 'height' => 58, 'alt' => 'The Hebrew University of Jerusalem Logo')),
      '#options' => array(
        'external' => TRUE,
        'html' => TRUE,
        'attributes' => array(),
      ),
    ),
  );

  return $header;
}

/**
 * Returns a build array for the standard branding footer region (copyright).
 *
 * @return array
 *   A build array ready to render footer info.
 */
function huji_branding_footer() {
  $footer = array();
  $footer['huji_container'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'copyright',
      ),
    ),
    'copyright' => array(
      '#markup' => l(t('<div class="huji-copyright">Copyright &copy; The Hebrew University of Jerusalem</div>'), 'http://new.huji.ac.il/en/page/479', array('html' => TRUE)),
    ),
    'credits' => array(
      '#markup' => t('<div class="credits">Developed by <a href="http://openscholar.gizra.com">Gizra</a></div>'),
    ),
  );

  return $footer;
}

/**
 * Implements hook_form_alter().
 */
function huji_form_alter(&$form, &$form_state, $form_id){

//change login form for huji: hide common login and add link to SSO login

  if (!in_array($form_id, array('user_login', 'user_login_block'))) {
    return;
  }

  $form['#attached']['js'] = array(drupal_get_path('module', 'huji') . '/js/login.js');
  $form['#prefix']= '<a href="http://scholars.huji.ac.il/saml_login" >HUJI Staff log in here </a><br> <a href="javascript:toggle();" id="loginlink" >
Login form for Admins and Testers here</a>  <div id="localogin" style="display: none;" >';
  $form['#suffix']="</div>";

}
